{{- if .Values.openshift -}}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ include "kogito-app.fullname" . }}-mgmt-console
  labels:
    {{- include "kogito-app.labels" . | nindent 4 }}
spec:
  to:
    kind: Service
    name: {{ include "kogito-app.fullname" . }}-mgmt-console
  port:
    targetPort: {{ .Values.service.targetPort }}
{{- end }}