apiVersion: v1
kind: Service
metadata:
  name: {{ include "kogito-app.fullname" . }}-mgmt-console
  labels:
    {{- include "kogito-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.mgmtService.port }}
      targetPort: {{ .Values.mgmtService.targetPort }}
      nodePort: {{ .Values.mgmtService.nodePort }}
      protocol: TCP
      name: http
  selector:
    {{- include "kogito-app.selectorLabels" . | nindent 4 }}