apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.postgresqlConfigMap }}
  labels:
    {{- include "kogito-app.labels" . | nindent 4 }}
data:
  QUARKUS_DATASOURCE_DB-KIND: postgresql
  QUARKUS_DATASOURCE_USERNAME: kogito-user
  QUARKUS_DATASOURCE_PASSWORD: kogito-pass
  QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://{{ include "kogito-app.postgresqlName" . }}:5432/kogito
  kafka.bootstrap.servers: {{ include "kafka.fullname" . }}-0.{{ include "kafka.fullname" . }}-headless.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}:{{ .Values.service.port }}
  ENABLE_EVENTS: "true"
