apiVersion: app.kiegroup.org/v1beta1
kind: KogitoSupportingService
metadata:
  name: {{ .Release.Name }}-data-index
  labels:
    {{- include "kogito-app.labels" . | nindent 4 }}
spec:
  serviceType: DataIndex
  replicas: 1
  image: quay.io/kiegroup/kogito-data-index-postgresql
  infra:
    - {{ .Release.Name }}-kafka-infra
  env:
    - name: QUARKUS_DATASOURCE_DB-KIND
      valueFrom:
        configMapKeyRef:
          name: {{.Values.postgresqlConfigMap}}
          key: QUARKUS_DATASOURCE_DB-KIND
    - name: QUARKUS_DATASOURCE_USERNAME
      valueFrom:
        configMapKeyRef:
          name: {{.Values.postgresqlConfigMap}}
          key: QUARKUS_DATASOURCE_USERNAME
    - name: QUARKUS_DATASOURCE_PASSWORD
      valueFrom:
        configMapKeyRef:
          name: {{.Values.postgresqlConfigMap}}
          key: QUARKUS_DATASOURCE_PASSWORD
    - name: QUARKUS_DATASOURCE_JDBC_URL
      valueFrom:
        configMapKeyRef:
          name: {{.Values.postgresqlConfigMap}}
          key: QUARKUS_DATASOURCE_JDBC_URL
